name: Java CI

on: [push]

jobs:
  build:
    runs-on: windows-latest # <-- Теперь сборка будет запускаться на Windows!

    steps:
      - uses: actions/checkout@v4

      # Установка JDK 17 для Windows
      - name: Set up JDK 17
        uses: actions/setup-java@v5 # ОБНОВЛЕНО! v4 устарела.
        with:
          distribution: 'temurin'
          java-version: "17"

      # Запускаем тесты через Gradle Wrapper для Windows
      # ВАЖНО: используйте /gradlew.bat вместо ./gradlew
      - run: /gradlew.bat test --no-daemon
